import dynamic from "next/dynamic";
import Link from "next/link";
import Script from "next/script";
import { brand } from "@hexxon/brand";
import { Badge, LeveyJenningsChart } from "@hexxon/ui";
import ContactForm from "./components/contact-form";
import HexSignalField from "./components/hex-signal-field";
import { BrandLockup } from "./components/hexxon-mark";
import MobileNav from "./components/mobile-nav";
import ProductEcosystem from "./components/product-ecosystem";
import { MarketingAnalytics, TrackedAnchor } from "./components/analytics";
import { marketingCopy } from "../src/content";

const QualityGraph = dynamic(() => import("./components/quality-graph"), { loading: () => <section className="quality-graph quality-graph-loading" aria-label="Carregando visualização de qualidade" /> });
const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: brand.name, url: "https://hexxon.com.br", description: brand.description };

export default function MarketingPage() {
  return <main className="marketing-shell"><MarketingAnalytics /><Script id="hexxon-organization" type="application/ld+json" strategy="beforeInteractive">{JSON.stringify(organizationSchema)}</Script>
    <header className="marketing-header"><div className="marketing-container marketing-nav"><Link href="/" className="marketing-mark" aria-label={brand.name}><BrandLockup /></Link><nav aria-label="Navegação principal"><a href="#plataforma">Plataforma</a><a href="#produtos">Produtos</a><a href="#intelligence">Inteligência</a><a href="#seguranca">Segurança</a></nav><div className="nav-actions"><a className="nav-cta" href="#contato">Falar com a Hexxon <span aria-hidden="true">↗</span></a><MobileNav /></div></div></header>
    <section className="hero-section"><div className="hero-halo" aria-hidden="true" /><div className="marketing-container hero-layout"><div className="hero-copy"><span className="hx-eyebrow">Infraestrutura de qualidade / laboratórios modernos</span><h1>{marketingCopy.hero.title}</h1><p>{marketingCopy.hero.supporting}</p><div className="hero-actions"><TrackedAnchor className="hx-button" href="#plataforma">{marketingCopy.hero.primary} <span aria-hidden="true">↓</span></TrackedAnchor><TrackedAnchor className="text-action" href="#contato">{marketingCopy.hero.secondary} <span aria-hidden="true">↗</span></TrackedAnchor></div><div className="hero-index"><span>01 / 06</span><i /><span>SINAIS VINCULADOS</span></div></div><HexSignalField /></div></section>
    <section id="plataforma" className="platform-section"><div className="marketing-container"><div className="section-intro platform-intro"><span className="hx-eyebrow">Hexxon Cloud</span><h2 className="marketing-heading">Uma superfície operacional para o que sustenta a qualidade.</h2><p>Hexxon Cloud conecta evidências sem ocultar origem, responsável ou contexto.</p></div><div className="platform-stage"><div className="platform-stage-head"><span className="hx-mono">QUALITY / 01</span><Badge tone="warning">revisão necessária</Badge></div><LeveyJenningsChart /><div className="platform-stage-foot"><span>Referência: N2 / lote vinculado</span><span>Regra determinística + revisão humana</span></div></div></div></section>
    <section className="problem-section"><div className="marketing-container problem-layout"><div className="problem-ordinal">SINAL<br /><em>≠</em><br />CONTEXTO</div><div><span className="hx-eyebrow">O problema</span><h2 className="marketing-heading">A operação se fragmenta antes de a qualidade falhar.</h2><div className="problem-list"><p><span>01</span> Um dado sem ativo, lote ou evidência vira um ponto isolado.</p><p><span>02</span> Registro manual atrasa investigação e fechamento.</p><p><span>03</span> Alerta desconectado não explica o que revisar.</p></div></div></div></section>
    <section id="produtos" className="products-section"><div className="marketing-container"><div className="products-heading"><span className="hx-eyebrow">Ecossistema Hexxon</span><h2 className="marketing-heading">Seis domínios. Um contexto operacional.</h2><p>Escolha um ponto de entrada. Cada domínio mantém sua fronteira e revela conexões quando elas importam.</p></div><ProductEcosystem /></div></section>
    <QualityGraph />
    <section id="intelligence" className="intelligence-section"><div className="marketing-container intelligence-layout"><div><span className="hx-eyebrow">Hexxon Intelligence</span><h2 className="marketing-heading">Síntese assistiva. Decisão humana.</h2><p>Inteligência organiza sinais, evidencia relações e sugere próximos passos. Ela não libera resultados nem altera registros.</p><Link className="text-action" href="/products/intelligence">Conhecer Intelligence <span aria-hidden="true">↗</span></Link></div><div className="intelligence-terminal"><div><span>CONTEXT ASSEMBLY</span><span><i /> PRONTO</span></div><p>Variação identificada após troca de lote. Compare referência vigente, manutenção recente e evidência ambiental.</p><small>Assistência operacional · não é decisão clínica</small></div></div></section>
    <section className="trust-section" id="seguranca"><div className="marketing-container"><div className="trust-intro"><span className="hx-eyebrow">Segurança e conformidade</span><h2 className="marketing-heading">Evidência, isolamento e governança por desenho.</h2></div><div className="trust-grid"><div><span>01</span><strong>Tenant isolation</strong><p>Organization e Site delimitam a operação no backend e no banco.</p></div><div><span>02</span><strong>Audit by design</strong><p>Ação crítica deve produzir evidência, não apenas um log opcional.</p></div><div><span>03</span><strong>Assistive AI</strong><p>IA explica e sugere; responsáveis continuam no controle.</p></div></div><p className="compliance-note">A Hexxon não declara certificações nesta página. Qualquer requisito regulatório será tratado com evidência e escopo explícitos.</p></div></section>
    <section className="trace-section"><div className="marketing-container trace-layout"><div className="trace-diagram" aria-hidden="true"><span>RECEBIMENTO</span><i /><span>USO</span><i /><strong>EVENTO</strong></div><div><span className="hx-eyebrow">Rastreabilidade</span><h2 className="marketing-heading">A cadeia permanece legível do recebimento ao evento.</h2><p>Lotes, ativos, leituras e intervenções se tornam relações investigáveis — sem confundir coincidência e causalidade.</p></div></div></section>
    <section className="built-section"><div className="marketing-container built-layout"><span className="built-index">Built with laboratories,<br />not around them.</span><div><p className="built-lead">A Hexxon nasce de fluxos reais: onde a evidência se perde, o contexto quebra e a equipe precisa de clareza.</p><p>Esse aprendizado informa o produto sem importar hardcodes ou limitações de uma única operação.</p></div></div></section>
    <section className="cta-section"><div className="marketing-container"><span className="hx-eyebrow">Próximo sinal</span><h2>Transforme operação dispersa em qualidade legível.</h2><a className="hx-button" href="#contato">Falar com a Hexxon <span aria-hidden="true">↗</span></a></div></section>
    <section id="contato" className="contact-section"><div className="marketing-container contact-layout"><div className="contact-copy"><span className="hx-eyebrow">Contato</span><h2 className="marketing-heading">Comece pelo fluxo que mais precisa de contexto.</h2><p>A conversa parte da realidade do seu laboratório — e não de uma demonstração genérica.</p><div className="contact-lattice" aria-hidden="true"><span>INTERESSE</span><i /><span>LABORATÓRIO</span><i /><span>CONTATO</span><i /><strong>HEXXON</strong></div></div><ContactForm /></div></section>
    <footer className="marketing-footer"><div className="marketing-container"><div className="marketing-mark"><BrandLockup /></div><p>Quality infrastructure for modern laboratories.</p><div><a href="#plataforma">Plataforma</a><a href="#produtos">Produtos</a><a href="#contato">Contato</a></div><small>© {new Date().getFullYear()} {brand.name}. Nome de trabalho sujeito a validação jurídica.</small></div></footer>
  </main>;
}
