import dynamic from "next/dynamic";
import Link from "next/link";
import Script from "next/script";
import { brand } from "@hexxon/brand";
import { Badge, LeveyJenningsChart } from "@hexxon/ui";
import ContactForm from "./components/contact-form";
import { marketingCopy, products } from "../src/content";

const QualityGraph = dynamic(() => import("./components/quality-graph"), { loading: () => <section className="quality-graph quality-graph-loading" aria-label="Carregando visualização de qualidade" /> });
const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: brand.name, url: "https://hexxon.com.br", description: brand.description };

export default function MarketingPage() {
  return <main className="marketing-shell"><Script id="hexxon-organization" type="application/ld+json" strategy="beforeInteractive">{JSON.stringify(organizationSchema)}</Script>
    <header className="marketing-header"><div className="marketing-container marketing-nav"><Link href="/" className="marketing-mark" aria-label={brand.name}><i aria-hidden="true" />HEXXON <span>LABS</span></Link><nav aria-label="Navegação principal"><a href="#plataforma">Plataforma</a><a href="#produtos">Produtos</a><a href="#intelligence">Inteligência</a><a href="#seguranca">Segurança</a></nav><a className="nav-cta" href="#contato">Falar com a Hexxon <span aria-hidden="true">↗</span></a></div></header>
    <section className="hero-section"><div className="marketing-container hero-layout"><div><span className="hx-eyebrow">{marketingCopy.hero.eyebrow}</span><h1>{marketingCopy.hero.title}</h1><p>{marketingCopy.hero.supporting}</p><div className="hero-actions"><a className="hx-button" href="#plataforma">{marketingCopy.hero.primary} <span aria-hidden="true">↓</span></a><a className="text-action" href="#contato">{marketingCopy.hero.secondary} <span aria-hidden="true">↗</span></a></div><div className="hero-provenance"><span>Construída a partir de fluxos reais de laboratório.</span><span>Sem dados, clientes ou certificações inventadas.</span></div></div><div className="hero-instrument" aria-label="Visualização de sinais operacionais"><div className="instrument-topline"><span>OPERATIONS / SIGNAL FIELD</span><Badge tone="success">context linked</Badge></div><div className="instrument-orbit"><span className="orbit-core">HQ</span><span className="orbit-dot dot-a" /><span className="orbit-dot dot-b" /><span className="orbit-dot dot-c" /><span className="orbit-line line-a" /><span className="orbit-line line-b" /></div><div className="instrument-readout"><span>QO-01</span><strong>Contexto antes de conclusão.</strong><span>6 sistemas conectáveis</span></div></div></div></section>
    <section id="plataforma" className="marketing-section section-with-grid"><div className="marketing-container"><div className="section-intro"><span className="hx-eyebrow">A plataforma</span><h2 className="marketing-heading">Uma superfície operacional para tudo que sustenta a qualidade.</h2><p>Hexxon Cloud conecta evidências operacionais sem esconder a origem, o responsável ou o contexto de cada sinal.</p></div><div className="platform-stage"><div className="platform-stage-head"><span className="hx-mono">QUALITY / 01</span><Badge tone="warning">review required</Badge></div><LeveyJenningsChart /><div className="platform-stage-foot"><span>Referência: N2 / lote vinculado</span><span>Decisão: regra determinística + revisão humana</span></div></div></div></section>
    <QualityGraph />
    <section className="marketing-section problem-section"><div className="marketing-container split-section"><div><span className="hx-eyebrow">O problema</span><h2 className="marketing-heading">A operação se fragmenta antes de a qualidade falhar.</h2></div><div className="problem-list"><p><span>01</span> Uma leitura sem ativo, lote ou evidência vira um dado isolado.</p><p><span>02</span> Planilhas e registros manuais retardam investigação e fechamento.</p><p><span>03</span> Alertas desconectados não explicam o que precisa ser revisado.</p></div></div></section>
    <section id="produtos" className="marketing-section"><div className="marketing-container"><div className="section-intro products-intro"><span className="hx-eyebrow">Produtos conectáveis</span><h2 className="marketing-heading">Seis pontos de entrada. Uma linguagem operacional.</h2></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.slug}><div className="product-card-top"><span className="hx-mono">{product.mark}</span><span>{product.eyebrow}</span></div><h3>{product.name}</h3><p>{product.summary}</p><span className="product-signal">{product.signal}</span><Link href={`/products/${product.slug}`} className="product-link">Ver produto <span aria-hidden="true">↗</span></Link></article>)}</div></div></section>
    <section id="intelligence" className="marketing-section intelligence-section"><div className="marketing-container intelligence-layout"><div><span className="hx-eyebrow">Hexxon Intelligence</span><h2 className="marketing-heading">Inteligência que mostra o contexto. Pessoas que tomam a decisão.</h2><p>Assistência para explicar tendências, organizar evidências e sugerir próximos passos. Regras críticas continuam determinísticas, rastreáveis e sob revisão humana.</p><Link className="text-action" href="/products/intelligence">Conhecer Intelligence <span aria-hidden="true">↗</span></Link></div><div className="intelligence-terminal"><div><span>CONTEXT ASSEMBLY</span><span>ready</span></div><p>“Sinal de variação identificado após a troca de lote. Verifique a referência vigente, a manutenção mais recente e a evidência ambiental antes de concluir.”</p><small>Assistência operacional · não é decisão clínica</small></div></div></section>
    <section className="marketing-section trace-section"><div className="marketing-container trace-layout"><div className="trace-number">01<span>→</span>06</div><div><span className="hx-eyebrow">Rastreabilidade</span><h2 className="marketing-heading">Do recebimento ao evento de qualidade, sem perder a cadeia de contexto.</h2><p>Lotes, ativos, leituras e intervenções são pontos vinculáveis. A plataforma permite investigar relações sem confundir coincidência com causalidade.</p></div></div></section>
    <section id="seguranca" className="marketing-section security-section"><div className="marketing-container"><span className="hx-eyebrow">Segurança e conformidade</span><h2 className="marketing-heading">Projetada para evidência, isolamento e governança.</h2><div className="security-grid"><div><strong>Tenant isolation</strong><p>Organization e Site definem o escopo de cada operação, validado no backend e no banco.</p></div><div><strong>Audit by design</strong><p>Ações críticas são pensadas como eventos de auditoria, não como logs opcionais.</p></div><div><strong>Assistive AI</strong><p>IA sugere e explica; não libera resultados, não altera registros e não substitui responsáveis.</p></div></div><p className="compliance-note">A Hexxon não declara certificações nesta página. Requisitos regulatórios e validações serão tratados com evidência e escopo explícitos.</p></div></section>
    <section className="marketing-section integrations-section"><div className="marketing-container split-section"><div><span className="hx-eyebrow">Integrações</span><h2 className="marketing-heading">Integration-first sem dependência arquitetural de um fornecedor.</h2></div><div><p>Conectores, mapeamentos, execuções e reconciliações são tratados como capacidades de plataforma. Cada integração deve manter escopo, versão, idempotência e rastreabilidade próprios.</p><div className="integration-rail"><span>INSTRUMENTS</span><i /> <span>LIS</span><i /> <span>STORAGE</span><i /> <span>ANALYTICS</span></div></div></div></section>
    <section className="marketing-section built-section"><div className="marketing-container built-layout"><span className="built-index">Built with laboratories,<br />not around them.</span><div><p className="built-lead">A Hexxon nasce de problemas operacionais observados em laboratório: onde a evidência se perde, onde o contexto quebra e onde a equipe precisa de clareza, não de mais uma tela genérica.</p><p>O aprendizado de fluxos reais orienta o produto, mas não importa hardcodes, limitações de uma única operação ou decisões não generalizáveis.</p></div></div></section>
    <section className="cta-section"><div className="marketing-container"><span className="hx-eyebrow">Próximo sinal</span><h2>Transforme operação dispersa em qualidade legível.</h2><a className="hx-button" href="#contato">Falar com a Hexxon <span aria-hidden="true">↗</span></a></div></section>
    <section id="contato" className="marketing-section contact-section"><div className="marketing-container contact-layout"><div><span className="hx-eyebrow">Contato</span><h2 className="marketing-heading">Comece pela operação que mais precisa de contexto.</h2><p>Conte qual fluxo você quer tornar mais rastreável. A conversa começa pela realidade do seu laboratório.</p></div><ContactForm /></div></section>
    <footer className="marketing-footer"><div className="marketing-container"><div className="marketing-mark"><i aria-hidden="true" />HEXXON <span>LABS</span></div><p>Quality infrastructure for modern laboratories.</p><div><a href="#plataforma">Plataforma</a><a href="#produtos">Produtos</a><a href="#contato">Contato</a></div><small>© {new Date().getFullYear()} {brand.name}. Nome de trabalho sujeito a validação jurídica.</small></div></footer>
  </main>;
}
