package com.hexxon.api.lead;
import com.hexxon.api.lead.LeadDtos.*; import com.hexxon.api.notification.CommercialLeadNotificationService;
import java.time.Instant; import java.util.*; import org.jsoup.Jsoup; import org.jsoup.safety.Safelist; import org.springframework.data.domain.Sort; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class LeadService {
  private final ContactLeadRepository repository; private final LeadIntegrationProvider integrationProvider; private final CommercialLeadNotificationService notificationService;
  public LeadService(ContactLeadRepository repository, LeadIntegrationProvider integrationProvider, CommercialLeadNotificationService notificationService) { this.repository = repository; this.integrationProvider = integrationProvider; this.notificationService = notificationService; }
  @Transactional public LeadResponse create(CreateLeadRequest request) { if (request.website() != null && !request.website().isBlank()) throw new IllegalArgumentException("Invalid request."); ContactLead lead = new ContactLead(UUID.randomUUID(), clean(request.name()), clean(request.businessEmail()).toLowerCase(Locale.ROOT), clean(request.phone()), clean(request.laboratoryName()), clean(request.city()), clean(request.state()).toUpperCase(Locale.ROOT), clean(request.organizationSize()), request.siteCount(), request.interest(), clean(request.message()), clean(request.source()), clean(request.utmSource()), clean(request.utmMedium()), clean(request.utmCampaign()), Instant.now()); ContactLead saved = repository.save(lead); integrationProvider.register(saved); notificationService.notifyNewLead(saved); return response(saved); }
  @Transactional(readOnly = true) public List<LeadResponse> list() { return repository.findAll(Sort.by(Sort.Direction.DESC, "createdAt")).stream().map(this::response).toList(); }
  @Transactional public LeadResponse update(UUID id, UpdateLeadRequest request) { ContactLead lead = repository.findById(id).orElseThrow(() -> new NoSuchElementException("Lead not found")); lead.updateCommercialState(request.status(), clean(request.assignedTo()), clean(request.notes())); return response(lead); }
  private LeadResponse response(ContactLead lead) { return new LeadResponse(lead.getId(), lead.getName(), lead.getBusinessEmail(), lead.getLaboratoryName(), lead.getState(), lead.getInterest(), lead.getCreatedAt(), lead.getStatus(), lead.getAssignedTo(), lead.getNotes()); }
  private String clean(String value) { if (value == null) return null; String plain = Jsoup.clean(value, Safelist.none()); String compact = plain.replaceAll("\\s+", " ").trim(); return compact.isEmpty() ? null : compact; }
}
