import { Alert, Badge, Card, DataTable, Dropdown, LeveyJenningsChart, Sidebar, StatusCard, Tabs } from "@hexxon/ui";

const nav = [{ label: "Operations", mark: "01", active: true }, { label: "Quality control", mark: "02" }, { label: "Environment", mark: "03" }, { label: "Traceability", mark: "04" }, { label: "Assets", mark: "05" }];
export default function PlatformPage() {
  return <main className="hx-app"><Sidebar items={nav} /><section className="hx-main"><header className="platform-topline"><div><span className="hx-eyebrow">North Campus / Main lab</span><h1 className="platform-title">Operational signal</h1></div><div className="hx-cluster"><Badge tone="success">Live system</Badge><Dropdown label="Aug 29, 2026" items={["Today", "Last 7 days", "Last 30 days"]} /></div></header><Tabs tabs={["Overview", "Exceptions", "Evidence", "Activity"]} />
  <div className="hx-dashboard-grid" style={{ marginTop: 18 }}><StatusCard label="QC acceptance" value="98.4%" delta="+1.2 pts / 30 days" /><StatusCard label="Open signals" value="04" delta="2 need a review" tone="warning" /><StatusCard label="Traceability" value="100%" delta="No unlinked lots" /><StatusCard label="Assets due" value="02" delta="Next 7 days" tone="danger" />
  <Card className="hx-span-2 chart-card" raised><LeveyJenningsChart /></Card><Card className="hx-span-2"><div className="hx-eyebrow" style={{ color: "var(--text-secondary)" }}>Priority queue</div><div className="hx-stack" style={{ marginTop: 14 }}><Alert title="Control measurement needs review" tone="warning">Glucose N2 is at 2.1 SD. The deterministic rule engine retains the decision.</Alert><Alert title="Preventive maintenance due" tone="danger">Analyzer A-04 is due in 48 hours. Assign the intervention before the next run.</Alert></div></Card>
  <div className="hx-span-3"><DataTable columns={["Signal", "Site", "Evidence", "State", "Updated"]} rows={[["QC / Glucose N2", "North Campus", "Rule 1-2s", <Badge key="a" tone="warning">Review</Badge>, "12 min ago"], ["Asset / A-04", "North Campus", "Maintenance plan", <Badge key="b" tone="danger">Due soon</Badge>, "34 min ago"], ["Trace / RGT-092", "Central Lab", "Lot linked", <Badge key="c" tone="success">Nominal</Badge>, "1 h ago"]]} /></div><Card><span className="hx-eyebrow" style={{ color: "var(--text-secondary)" }}>Audit flow</span><p className="hx-muted" style={{ lineHeight: 1.55 }}>Every critical action is written as evidence, not activity noise.</p></Card></div>
  </section></main>;
}
